const TYPES = {
  ADD_REQUEST: `ADD_REQUEST`,
  CHANGE_VISIBILITY_FILTER: 'CHANGE_VISIBILITY_FILTER',
  COMPLETE_TASK: 'COMPLETE_TASK',
  UNDO_TASK: 'UNDO_TASK',
  DELETE_TASK: 'DELETE_TASK'
};

export default TYPES;
